projects/djangotuts/api/urls.py
from django.urls import include, path
from . import views
urlpatterns = [
    path("", views.index, name="home"),    
    path("register/", views.register, name="register"),
    path("articles/", views.ArticleAPIView.as_view(), name="articles"),
    path("articles/<int:pk>/", views.article_details, name="details")
]

projects/djangotuts/crunchit/urls.py
from django.urls import path

from . import views


app_name = 'crunchit'

urlpatterns = [
    path("", views.article_home_view, name="home"),
    path("shop", views.shop_view, name="shop"),
    path("add-product", views.query_view, name="search"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login, name="login"),
]

projects/djangotuts/djangotuts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("crunchit/", include("crunchit.urls")),
    path("api/", include("api.urls")),
    path("", TemplateView.as_view(template_name="index.html")),

]

projects/djangotuts/crunchit/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Product(models.Model):
    item_name = models.TextField(max_length=120, blank=False)
    date_created = models.DateTimeField(auto_now_add=True)
    stock_amount = models.IntegerField(blank=False)
    featured = models.BooleanField(default=False)
    amount_sold = models.IntegerField(default=0)
    company = models.TextField(max_length=120)
    image = models.ImageField(upload_to='pictures', max_length=None)

    def top_selling(self):
        return self.amount_sold >= 100

    def __str__(self):
        return self.item_name


class Users(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    phone_number = models.CharField(blank=True, max_length=14)
    password = models.CharField(max_length=255)
    time_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_name

projects/djangotuts/crunchit/forms.py
from django import forms


class UserForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=254)
    phone_number = forms.CharField(max_length=14)
    password = forms.CharField(max_length=255, widget=forms.PasswordInput())

class LoginForm(forms.Form):
    email = forms.CharField(max_length=254)
    password = forms.CharField(max_length=255, widget=forms.PasswordInput())

projects/djangotuts/crunchit/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Product, Users
from django.urls import reverse
from .forms import UserForm, LoginForm
# Create your views here.

def article_home_view(request):
    return render(request, "index.html", {})


def index_view(request):
    try:
       product_data = Product.objects.order_by("-amount_sold")[:5]
       top_products = []
       for product in product_data:
           if product.top_selling():
               top_products.append(product)


       all_products = Product.objects.all()
       featured_products = []
       for product in all_products:
           if product.featured is True:
               featured_products.append(product)

    except Product.DoesNotExist:
        return Http404("No top selling product")
    context = {
        'product_data': top_products,
        'featured': featured_products[:5]
    }

    return render(request, "home.html", context)

def shop_view(request):
    try:
        product_data = Product.objects.order_by("-featured")

    except Product.DoesNotExist or KeyError:
        Http404("No Item in shop")

    context = {
        'list': product_data
    }

    return render(request, "shop.html", context)

def query_view(request):
    search = request.GET['search'].strip()

    try:
        searched_product = Product.objects.get(item_name = search)


    except Product.DoesNotExist:
        return HttpResponse(f"We could not find any records matching the key word '{search}'")

    return HttpResponse(str(searched_product) + " was Found in store, buy here: http://localhost:8000/crunchit/shop ")

def register_view(request):
    my_form = UserForm()

    if request.method == "POST":
        my_form = UserForm(request.POST)
        if my_form.is_valid():
            validated_data = my_form.cleaned_data
            u = Users(**validated_data)
            u.save()
            my_form = UserForm()
        else:
            print(my_form.errors)




   
    context = {
        'form': my_form
    }
    return render(request, "new.html", context)

def login(request):
    form = LoginForm()

    if request.method=="POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            form_email = form.cleaned_data['email']
            email = Users.objects.filter(email=form_email)
            print(email)
    return render(request, "loggedin.html", {
        'form': form
    })

projects/djangotuts/crunchit/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Crunchit! and buy it</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.j s"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
  <link href="{% static 'css/home.css' %}" rel="stylesheet"  />
  </head>
  <body>
<nav class="nav-bar">
  <div class="container-fluid">

  <div class="nav-bar-items">
      <a href="/crunchit"><img src="{% static 'assets/logo.png' %}" alt="logo" width="50" height="50" /></a>

    <ul>
      <li><a href="{% url 'crunchit:shop' %}">Shop</a></li>
      <li><a href="#">Products</a></li>
    </ul>
    <form action="{% url 'crunchit:search' %}" class="navbar-fm">
      <input type="text" name="search" />
      <button>Search</button>
    </form>
    <div class="navbar-end">
    <p class="cart"><a href="#">Cart</a></p>
    <button><a href="/twitter"><i class="fab fa-twitter"></i></a></twitter>
      <button><a href="/facebook">Facebook</a></twitter>
      <a href="{% url 'crunchit:register' %}">Register</a>
     </div>
  </div>


  </div>
</nav>
    {% block content %}



    {% endblock %}
  </body>
</html>

projects/djangotuts/crunchit/templates/home.html
{% extends "base.html" %} {% block content %}
{% load static %}

<h4>Top Selling</h4>

<div class="top-sales">
  {% if product_data %} {% for product in product_data %}

  <div class="card card{{product.id}}">
    <img src="" alt="image{{product.id}}" class="sale-images" />
    <h3>{{product.item_name}}</h3>
    <i>{{product.company}}</i>
    <div class="btn-btns">
      <button>Buy</button>
      <button>Cart</button>
    </div>
    
  </div>
  {% endfor %} {% else %}
  
  <p>Loading...</p>
  {% endif %}
  <button>Next</button>
</div>
<div class="banner-ads">
<div class="inner1">
  <h3>Black Friday Sales</h3>
  <p>Shop your favourite items with over 50% off</p>
  </div>
  <button><a href="{% url 'crunchit:shop' %}">Shop now</a></button>
</div>
<h4>Featured Products</h4>
<div class="featured">
  {% for product in featured %}
  <div class="card card{{product.id}}">
    <img src="{{ product.image }}" alt="image{{product.id}}" class="sale-images" />
    <p>{{ product.image }}</p>
    <h3>{{product.item_name}}</h3>
    {% if product.featured is True %} <p>-50 off<p> {% endif %}
    <i>{{product.company}}</i>
    <div class="btn-btns">
      <button>Buy</button>
      <button>Cart</button>
    </div>
    <button>Next</button>
  </div>
  {% endfor %}
  <button>Next</button>
</div>

{% endblock %}

projects/djangotuts/crunchit/templates/loggedin.html
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<button>Login</button>
</form>

projects/djangotuts/crunchit/templates/new.html
<h1>Hello</h1>
<h3>Register with us</h3>
{{ error }}
<form method="POST" id="register">
{% csrf_token %}
{{ form.as_p }}
<button>Save</button>
<a href="{% url 'crunchit:login' %}">Login</a>
</form>

projects/djangotuts/crunchit/templates/shop.html
{% extends 'base.html' %} {% block content %}
<div class="shop-container">
  {% if list %} {% for product in list %}

  <div class="card card{{forloop.counter}}">
    <img src="" alt="image{{product.id}}" class="sale-images" />
    <h3>{{product.item_name}}</h3>
    <i>{{product.company}}</i>
    <div class="btn-btns">
      <button>Buy</button>
      <button>Cart</button>
    </div>
    </div>

    {% endfor %}
  

  {% else %}
  <p>Loading...</p>

  {% endif %} {% endblock %}
</div>